version: "3.9"

services:
  postgres:
    container_name: ppostgres.postgres
    image: "postgres:15-alpine"
    env_file:
      - .env
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASS
      POSTGRES_DB: $DATABASE_NAME
    volumes:
      - "ppostgres.postgres.data:/var/lib/postgresql/data:rw"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${DATABASE_NAME} -U $${DATABASE_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  web:
    container_name: web
    build: .
    ports:
      - 8004:8000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres

volumes:
  ppostgres.postgres.data: {}